# Site settings
author: Michael Calkins
title: Stop Wasting Time
header-img: img/home-bg.png
email: m.calkins576@gmail.com
copyright_name: Michael Calkins
description: > # this means to ignore newlines until "baseurl:"
  and start learning again
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  C-Mike576

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
